bluespot/base/utils/forms.py
def print_errors(form):
    """Flashes form errors"""
    for field, errors in form.errors.items():
	for error in errors:
	    print "Error in the %s field - %s" % (getattr(form, field).label.text,error)

def get_errors(form):
    """ Return form errors as string """
    form_errors = ""
    for field, errors in form.errors.items():
        for error in errors:
            form_errors = form_errors+ "Error in the %s field - %s </br>" % (getattr(form, field).label.text,error)
    return form_errors

bluespot/guest/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, HiddenField
from wtforms.validators import Required,DataRequired,Email

from .const import form_fields_dict

class FacebookTrackForm(Form):

    authlike = HiddenField("Auth Like")
    authpost = HiddenField("Auth Post")

def generate_emailform(form_fields):
    class F(Form):
        pass
    for key in form_fields:
        if key in ['firstname','lastname','email','phonenumber']:
            if  key == 'email':
                setattr(F, key, TextField(form_fields_dict[key],validators =[DataRequired(),Email()]))
            else:
                setattr(F, key, TextField(form_fields_dict[key],validators = [Required()]))        

    return F()

bluespot/__init__.py
from flask import render_template,redirect,url_for

from flask.ext.assets import Environment
import re

#import basic utlities
from base.utils.core import (load_blueprint_settings, load_blueprints,	    error_handler,)


#import bundles
from assets import bundles


import os
import yaml

from flask import Flask as BaseFlask, Config as BaseConfig

class Config(BaseConfig):
    """Flask config enhanced with a `from_yaml` method."""
    
    def from_yaml(self, config_file):
       
        with open(config_file) as f:
            c = yaml.load(f)
          
        for key in c.iterkeys():
            if key.isupper():
                self[key] = c[key]
                #print key

                
class Flask(BaseFlask):
    """Extended version of `Flask` that implements custom config class"""
    
    def make_config(self, instance_relative=False):
        root_path = self.root_path
        if instance_relative:
            root_path = self.instance_path
        return Config(root_path, self.default_config)

def create_app(mode="development"):
    """Create webapp instance."""
    app = Flask(__name__)
    #Initilise DB
    from bluespot.extensions import db
    db.init_app(app)
    # Load the default configuration
    app.config.from_object('config.default')
    #Load user specified config
    app.config.from_yaml(os.path.join(app.root_path,'..','config.yaml'))
    #initlize assets
    assets = Environment(app)
    assets.register(bundles)    
    # simple load all blueprint settings, enabled in config
    load_blueprint_settings(app,blueprint_path='bluespot')
    # simple load all blueprints, enabled in config
    load_blueprints(app,blueprint_path='bluespot')
    # Enable DebugToolbar on debug
    # Enable error handler on productive mode
    if app.config['DEBUG']:
        from flask_debugtoolbar import DebugToolbarExtension
        DebugToolbarExtension(app)
        app.logger.error( "DEV")

    else:
        # add errorhandler
        #error_handler(app)
        app.logger.error( "PROD")


    @app.route("/")
    def home():
        return "OK"

    return app


def remove_db_session(exception=None):
    db_session.remove()

bluespot/admin/__init__.py
# -*- coding: utf-8 -*-
from views import bp

bluespot/admin/views.py
from functools import wraps
from flask import request, Response,Blueprint,render_template,jsonify,current_app,abort,redirect,url_for

from bluespot.extensions import db
from bluespot.base.utils.helper import format_url
from bluespot.base.utils.forms import print_errors,get_errors
from bluespot.guest.models import Guest

bp = Blueprint('admin', __name__,template_folder='templates')


def check_auth(username, password):
    """This function is called to check if a username /
    password combination is valid.
    """
    if username == current_app.config['LANDINGSITE']['adminusername'] and password == current_app.config['LANDINGSITE']['adminpassword'] :
        return 1
    else:
        return None

def authenticate():
    """Sends a 401 response that enables basic auth"""
    return Response(
    'Could not verify your access level for that URL.\n'
    'You have to login with proper credentials', 401,
    {'WWW-Authenticate': 'Basic realm="Login Required"'})

def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated

@bp.route('/')
@requires_auth
def client_index( ):
    items = Guest.query.filter_by().all()
    return render_template('admin/dashboard.html',items=items)
    

bluespot/guest/__init__.py
# -*- coding: utf-8 -*-
from views import bp

bluespot/guest/views.py
from flask import Blueprint,render_template,jsonify,request,current_app,abort,redirect,url_for
from functools import wraps
from sqlalchemy import and_,or_
import uuid
from functools import wraps
from facebook import get_user_from_cookie, GraphAPI
from unifi.controller import Controller
import datetime
import random
from .models import Guest,Device,Guestsession,Guesttrack,Facebookauth
from .const import *
from .forms import FacebookTrackForm,generate_emailform
from bluespot.extensions import db
from bluespot.base.utils.helper import format_url
from bluespot.base.utils.forms import print_errors,get_errors


bp = Blueprint('guest', __name__,template_folder='templates')



@bp.route('/')
def client_index( ):
    #return render_template('user/login.html')
    abort(404)

@bp.route('/s/<site_id>/',methods = ['GET', 'POST'])
def guest_portal(site_id):

    #--get all URL parameters, expected URL format--
    device_mac = request.args.get('id')
    ap_mac   = request.args.get('ap')   
    orig_url = request.args.get('url')   
  
    if not device_mac or not ap_mac:
        current_app.logger.error("Guest portal called with empty ap_mac/user_mac")
        abort(404)
    guest_device = None
    #create guest tracking entry
    track_id = str(uuid.uuid4())
    guest_track = Guesttrack(ap_mac=ap_mac,device_mac=device_mac,state=GUESTRACK_INIT,orig_url=orig_url,track_id=track_id)
    db.session.add(guest_track)
    #Initialize the session, check if the user has recently logged in 
    guest_session = Guestsession.query.filter( and_(Guestsession.mac==device_mac,Guestsession.state != SESSION_EXPIRED)).first() 
    #Check if the device was ever logged
    guest_device =  Device.query.filter(Device.mac==device_mac).first()
    if not guest_session:
        #create session
        guest_session = Guestsession(mac=device_mac,state=SESSION_INIT)
        db.session.add(guest_session)
        #check for guest device
        if guest_device:
            #device was logged once, add session to the device      
            guest_device.sessions.append(guest_session)
        else:
            #device was never logged, create a new device and add a session
            guest_device = Device(mac=device_mac,state=DEVICE_INIT)
            db.session.add(guest_device)
            guest_device.sessions.append(guest_session)
        db.session.commit()
    #session exists
    else:
        if not guest_device:
            current_app.logger.error("Guest Session exists, but Device not found in DB!! MAC:%s AP:%s"%(device_mac,ap_mac))
            abort(404)    
    #connect this session to our guest track entry
    guest_track.session = guest_session
    guest_session.guesttracks.append(guest_track)
    guest_track.state = GUESTRACK_SESSION
    db.session.commit()    
    if current_app.config['LANDINGSITE']['loginmethod'] ==1:
        #AUTH mode is set to social
        return redirect(url_for('guest.social_login',track_id=guest_track.track_id),code=302)        
    elif current_app.config['LANDINGSITE']['loginmethod'] ==2:
        #AUTH mode is set to social
        return redirect(url_for('guest.email_login',track_id=guest_track.track_id),code=302)   

   
@bp.route('/auth/guest/<track_id>')
def authorize_guest(track_id):
    '''Function called after respective auth mechanisms are completed
    
       This function send API commands to controller, redirect user to correct URL
    '''
    
    #
    #Validate track id and get all the needed variables
    guest_track = Guesttrack.query.filter_by(track_id=track_id).first()
    if not guest_track:
        current_app.logger.error("Called authorize_guest with wrong track ID:%s"%track_id)
        abort(404)
        
    #validate session associated with this track ID
    guest_session = Guestsession.query.filter_by(id=guest_track.session_id).first()
    if not guest_session:
        current_app.logger.error("Called authorize_guest with wrong Session from track ID:%s"%track_id)
        abort(404)   


    #Check if the session is authorized
    if not guest_session.state == SESSION_AUTHORIZED:
        current_app.logger.error("Called authorize_guest with wrong Non Authorized session with track ID:%s"%track_id)
        abort(404) 

    #Send  unifi API commands if the user has completed login
    if not current_app.config['NO_UNIFI'] :
        #code to send auth command to controller
        try:
            c =  Controller(current_app.config['LANDINGSITE']['unifihost'], current_app.config['LANDINGSITE']['unifiadmin'], current_app.config['LANDINGSITE']['unifipass'],current_app.config['LANDINGSITE']['unifiport'],current_app.config['LANDINGSITE']['unifiversion'],current_app.config['LANDINGSITE']['unifisiteid'])       
            c.authorize_guest(guest_track.device_mac,guest_session.duration,ap_mac=guest_track.ap_mac)    
        except:
            current_app.logger.exception('Exception occured while trying to authorize User')
            return "Error Occured!"
    
    #Code to handle guest after successful login 
    
    if current_app.config['LANDINGSITE']['redirecturl']:
        return redirect(format_url(current_app.config['LANDINGSITE']['redirecturl']))
    elif guest_track.orig_url is not None:
        #redirect User's URL
        return redirect(format_url(guest_track.orig_url))
    else:
        #redirect user to google.com
        return redirect(format_url("www.google.com"),code=302)

@bp.route('/tempauth/guest/<track_id>')
def temp_authorize_guest(track_id):
    '''Function for giving temporary internet access for a client
    
       This function send API commands to controller, return ok
    '''
    guest_track = Guesttrack.query.filter_by(track_id=track_id).first()
    if not guest_track:
        current_app.logger.error("Called temp_authorize_guest with wrong track ID:%s"%track_id)
        abort(404)
        
    #validate session associated with this track ID
    guest_session = Guestsession.query.filter_by(id=guest_track.session_id).first()
    if not guest_session:
        current_app.logger.error("Called temp_authorize_guest with wrong Session from track ID:%s"%track_id)
        abort(404)   
    guest_track.state =GUESTRACK_TEMP_AUTH
    db.session.commit()

    #get details from track ID and authorize
    if not current_app.config['NO_UNIFI'] :
        try:
            c =  Controller(current_app.config['LANDINGSITE']['unifihost'], current_app.config['LANDINGSITE']['unifiadmin'], current_app.config['LANDINGSITE']['unifipass'],current_app.config['LANDINGSITE']['unifiport'],current_app.config['LANDINGSITE']['unifiversion'],current_app.config['LANDINGSITE']['unifisiteid'])       
            c.authorize_guest(guest_track.device_mac,5,ap_mac=guest_track.ap_mac)    
        except:
            current_app.logger.exception('Exception occured while trying to authorize User')
            return jsonify({'status':0,'msg': "Error!!"})
        return jsonify({'status':1,'msg': "DONE"})
    else:
        return jsonify({'status':1,'msg': "DEBUG enabled"})

@bp.route('/social/guest/<track_id>',methods = ['GET', 'POST'])
def social_login(track_id):
    ''' Function to called if the site is configured with Social login    
    
    '''
    #
    #Validate track id and get all the needed variables
    guest_track = Guesttrack.query.filter_by(track_id=track_id).first()
    if not guest_track:
        current_app.logger.error("Called social_login with wrong track ID:%s"%track_id)
        abort(404)
        
    #validate session associated with this track ID
    guest_session   = Guestsession.query.filter_by(id=guest_track.session_id).first()
    guest_device    = Device.query.filter_by(id=guest_session.device_id).first()
  
    if not guest_session or not guest_device :
        current_app.logger.error("Called social_login with wrong Session/Device/Wifisite from track ID:%s"%track_id)
        abort(404) 
    #
    #Check if the device already has a valid auth
    if  guest_device.state == DEVICE_AUTH:
        #Device has a guest element and is authorized
        guest_session.state = SESSION_AUTHORIZED
        guest_track.state   = GUESTRACK_SOCIAL_PREAUTH
        guest_device.state  = DEVICE_AUTH
        db.session.commit()
        #redirect to authorize_guest
        return redirect(url_for('guest.authorize_guest',track_id=guest_track.track_id),code=302)
    else:
        #show the configured landing page
        
        return get_landing_page(app_id=current_app.config['LANDINGSITE']['fbappid'],track_id=track_id )

@bp.route('/facebook/check/<track_id>',methods = ['GET', 'POST'])
def facebook_login(track_id):
    ''' Function to called if the site is configured for advanced facebook authentication.
    
    '''
    #fbtrackform = FacebookTrackForm()
    auth_like = None
    auth_post = None
    #if fbtrackform.validate_on_submit():
    if request.method == 'POST':
        auth_like = request.form['authlike']
        auth_post = request.form['authpost']
    # Attempt to get the short term access token for the current user.
    check_user_auth = get_user_from_cookie(cookies=request.cookies, app_id=current_app.config['LANDINGSITE']['fbappid'],app_secret=current_app.config['LANDINGSITE']['fbappsecret'])
    current_app.logger.debug("APPID:%s Secret:%s"%(current_app.config['LANDINGSITE']['fbappid'],current_app.config['LANDINGSITE']['fbappsecret']))
    if not check_user_auth or not check_user_auth['uid']:
        #
        #User is not logged into DB app, redirect to social login page
        print check_user_auth

        return redirect(url_for('guest.social_login',track_id=track_id),code=302)
    #Validate track id and get all the needed variables
    guest_track = Guesttrack.query.filter_by(track_id=track_id).first()
    if not guest_track:
        current_app.logger.error("Called authorize_guest with wrong track ID:%s"%track_id)
        abort(404)
        
    #validate session associated with this track ID

bluespot/templates/newmacros.html
{% macro render_guest(form) -%}

{{form.hidden_tag() }}
{% for field in form %}
{% if field.type not in ['CSRFTokenField', 'HiddenField'] and field.id  not in [ 'newsletter','subscribe'] %}
<!--  {{ field() }}-->
<div class="form-group {% if field.errors %}error{% endif %}">
     <label class="control-label col-xs-4 col-xs-offset-1  col-md-3 col-md-offset-2 form-label">{{ field.label(for=field.id) }}</label>
      {% if field.id   in [ 'gender',] %}
      <div class="col-xs-5 col-md-3 form-input">
              <select class="form-control input-guest" id="gender-select" > <option value="1" >Male</option><option value="2" >Female</option></select>
        </div><!-- //form-input-->



     <div style="display:none;">
                {{field( **{'value':'1'} )}}

        </div> 
       {% else %}
      <div class="col-xs-5 col-md-3 form-input">
                {{ field(class_="form-control input-guest")}}
	</div><!-- //form-input-->

      {% endif %}
        {% if field.errors %}
              {% for error in field.errors %}
               <span class="help-inline text-red">[{{ error }}]</span><br>
              {% endfor %}
        {% endif %}


  </div><!-- //form-group-->
{% endif %}
{% endfor %}
{%endmacro%}

bluespot/templates/social_landing.html
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, target-densitydpi=device-dpi, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <!-- These are Open Graph tags.-->
    <meta property="fb:app_id" content="{{ app_id }}" />
    <!-- Bootstrap -->
    

    <!-- Botstrap 3.0.2 --> 
        <link href="{{ url_for('static', filename='guest/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='guest/css/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="{{ url_for('static', filename='guest/css/font-awesome.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='guest/css/landing.css')}}" rel="stylesheet" type="text/css" />
    
	<style>

/* http://css-tricks.com/perfect-full-page-background-image/ */
html {
	background: url( {%if clientpage.bgfile%}{{  clientpage['bgfile']}}{%endif%}) no-repeat center center fixed; 
	-webkit-background-size: 100% 100% !important;
	-moz-background-size: 100% 100% !important;
	-o-background-size: 100% 100% !important;
	background-size: 100% 100% !important;
}
html,body,section{height:100%;}
body {	

	font-family: "Open Sans",serif;
	background: transparent;
}

.bg-landing{

}
.circle {
	margin-left: auto;
	margin-right: auto;
	border-radius: 50%;
	position: relative;
	padding-top:50%;
	background: {{clientpage['wifilogocolor']}};
}

.circle-border {
	
}

.circle-solid{
	background-color: whitesmoke;
}

.circle:before {
	content: "";
	display: block;
	padding-top: 100%;
}

.circle-inner {
	position: absolute;
	top: 0;
	left: 0;
	bottom: 0;
	right: 0;
	text-align: center;
	
	border-radius: 50%;
	padding:12%;
	border-color:{{clientpage['bgcolor']}};
}
.circle-inner img{


}
.score-text {

	display: block;
	margin: 20px;
}
.img-responsive.img-center {
    margin: 0 auto;
} 
/*------------- Circle wifi logo styles -------------end */

.row-header{
	background-color: {{clientpage['bgcolor']}};
	font-family:{{clientpage['base_font']}}
	padding-top: 20px;
	padding-bottm: 20px;
}
.client-logo{

}
.row-top-content{

	color: {{clientpage['toptextcolor']}};
	background-color: {{clientpage['topbgcolor']}};
	padding-bottom: 10px;
	padding-top: 10px;
	font-family:{{clientpage['topfont']}}
}
.row-middle-content{
	padding-top: 10px;	
	color: {{clientpage['middletextcolor']}};
	background-color: {{clientpage['middlebgcolor']}};
	font-family:{{clientpage['middlefont']}}

}
.input-guest{
	color: {{clientpage['middletextcolor']}};
	background-color: {{clientpage['middlebgcolor']}};
    border-color: {{clientpage['middletextcolor']}};
	font-family:{{clientpage['middlefont']}}
}
.row-bottom {
	padding-top: 5px;
	padding-bottom: 5px;
	background-color: {{clientpage['bottombgcolor']}};
	color:{{clientpage['bottomtextcolor']}};
	font-family:{{clientpage['bottomfont']}}
}		
.row-bottom a{
	color:{{clientpage['bottomtextcolor']}};
	font-family:{{clientpage['bottomfont']}}
}				
.row-footer {
	background-color: {{clientpage['footerbgcolor']}};
	padding-top: 5px;
	padding-bottom: 5px;
	color:{{clientpage['footertextcolor']}};
	font-family:{{clientpage['footerfont']}}
}

.btn-guest {
    background-color: {{clientpage['btnbgcolor']}};
    border-color: {{clientpage['btnlinecolor']}};
    color: {{clientpage['btntxtcolor']}};
	border-radius: 6px;
    font-size: 18px;
    line-height: 1.33;
    padding: 10px 16px;
	font-family:{{clientpage['bottomfont']}}
}
ul{
	list-style-type: none;

}
.btn-xlarge {
    padding: 20px 38px;
    font-size: 22px; //change this to your desired size
    line-height: normal;
    -webkit-border-radius: 8px;
       -moz-border-radius: 8px;
            border-radius: 8px;
}



</style>
</head>
<body>
	<div class="container bg-landing">
		<div class="row row-header">
			<div class="col-md-12   col-sm-12 col-xs-12 ">	
				<div class="row client-logo"> 
					<img src="{%if clientpage.logofile%}{{  clientpage['logofile'] }}{%endif%}" class="img-responsive center-block">
				</div>
			</div>							
		</div><!-- //header-->
		<div class="row row-top-content">
			<div class="col-top-content">				
				<p class="midle-top-cont text-center">{{clientpage['toptextcont|safe']}}</p>
			</div>
		</div><!-- //top content-->
		<div class="row row-middle-content " id="detailsDiv">
			
		</div><!-- //middle content-->
		<div class="row row-bottom">			
			<div id="login-buttons">	
					<p class="text-center login-button">
	                    <button type="submit" class="btn btn-guest " id='loginfb' >Login Using Facebook</button>
					</p>          
            </div>
			<div class="col-xs-offset-2 col-sm-offset-3 col-md-offset-3">
					<p class="bottom-text"> <input type="checkbox" id="agreetos" value="">
					By Clicking you are agreeing to our 
					{% if clientpage.tosfile %} 
					<a href="{{ url_for('static', filename='uploads/'+clientpage.tosfile)}}"><u>USER AGREEMENT</u></a>
					{% else %}USER AGREEMENT{%endif%}</p><p class="bottom-text" ></p>
			</div>
		</div><!-- //bottom content-->
		<div class="row row-footer">
			<ul class=" text-center">
                {{clientpage['copytextcont|safe']}}
			</ul>
                        <!-- License start you are free to modify the source as long as below content is kept untouched -->
            <div class="page-footer-inner text-center">
             Powered by <a href="http://www.unifispot.com" title="Captive portal with Socil Login and Data collection" target="_blank">Unifispot</a>
            </div>
		</div><!-- //footer content-->

	</div> <!-- //container -->
	 <!-- jQuery 2.0.2 -->
     <script src="{{ url_for('static', filename='guest/js/jquery-2.0.2.min.js')}}" type="text/javascript"></script>
        <!-- jQuery UI 1.10.3 -->
       <script src="{{ url_for('static', filename='guest/js/jquery-ui-1.10.3.min.js')}}" type="text/javascript"></script>
        <!-- Bootstrap -->
        <script src="{{ url_for('static', filename='guest/js/bootstrap.min.js')}}" type="text/javascript"></script>
        <script src="{{ url_for('static', filename='guest/js/jquery.blockui.min.js')}}" type="text/javascript"></script>
        
	<script type="text/javascript">
	$(document).ready(function() {
        $.ajaxSetup({ cache: true });
        $('#loginfb').click(function(){
            if ($("#agreetos").prop('checked') == true){

                $.ajax({
                    type: 'get',
                    url: '/guest/tempauth/guest/{{track_id}}',
                    data: {},
                    success: function(data) {
                        if (data.status) {
                            $.blockUI({ message: '<h2><img src="/static/img/loading-spinner-blue.gif" /> Loading..</h2>',css: { 
                                        border: 'none', 
                                        padding: '15px', 
                                        backgroundColor: '#000', 
                                        '-webkit-border-radius': '10px', 
                                        '-moz-border-radius': '10px', 
                                        opacity: .5, 
                                        color: '#fff' 
                                    } });

                            var tid = setInterval(function() {
                                $.getScript('//connect.facebook.net/en_US/sdk.js', function(){
                                    clearInterval( tid );
                                    $.unblockUI();
                                    FB.init({
                                          appId: '{{app_id}}',
                                          status: false,
                                          cookie: true,
                                          version: 'v2.3' // or v2.0, v2.1, v2.0
                                     });                                      
                                    FB.getLoginStatus(function(response) {
                                        console.log(response);
                                        //console(response);
                                        if (response.status === 'connected') {
                                            window.location.href = "{{url_for('guest.facebook_login',track_id=track_id,_external=True)}}";
                                          // Logged into your app and Facebook.
                                          //testAPI();
                                          
                                        }
                                        else{
                                            uri = '{{request.url}}';
                                             window.location = encodeURI("https://www.facebook.com/dialog/oauth?client_id={{app_id}}&scope=email&redirect_uri="+uri+"&response_type=token");
                                        }

                                    }); 
                                });

                            }, 5000); //5 seconds    

                    }

                }
                });
                    return false;
                
            }
            else{
                alert("Please accept the terms before proceeding");
                return false;
            }                
        });
    });
	</script>
</body>
</html>